# Generated by Django 4.2 on 2023-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit')], max_length=6)),
            ],
        ),
    ]
